apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alb-latitude-console-dev
  namespace: latitude-dev
  annotations:
   alb.ingress.kubernetes.io/group.name: latitude-dev-uiservices
   alb.ingress.kubernetes.io/load-balancer-name: latitude-dev-services
   alb.ingress.kubernetes.io/scheme: internal
   alb.ingress.kubernetes.io/target-type: ip
   kubernetes.io/ingress.class: alb
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: latitude-console
            port:
              number: 3000
        path: /*
        pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alb-latitude-console-qa
  namespace: latitude-qa
  annotations:
   alb.ingress.kubernetes.io/group.name: latitude-qa-uiservices
   alb.ingress.kubernetes.io/load-balancer-name: latitude-qa-services
   alb.ingress.kubernetes.io/scheme: internal
   alb.ingress.kubernetes.io/target-type: ip
   kubernetes.io/ingress.class: alb
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: latitude-console
            port:
              number: 3000
        path: /*
        pathType: ImplementationSpecific
